In [59]:
import numpy as np
import pandas as pd

In [78]:
D = 0.99
k = 1

In [79]:
def demurrage(preValue):
    value = preValue * D**(k*np.log(preValue))
    return value

In [80]:
A = {}
for i in range (0, 100, 10):
    if(i == 0):
        i = 1;
    temp = i
    A[i] = {}
    for j in range(0, 100, 10):
        if(j == 0):
            j = 1;
        temp = demurrage(temp)
        A[i][j] = temp

In [81]:
table = pd.DataFrame(A).transpose()

In [82]:
table

,1,10,20,30,40,50,60,70,80,90
1,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
10,9.771240,9.549933,9.335789,9.128526,8.927879,8.733593,8.545425,8.363141,8.186520,8.015347
20,19.406812,18.836917,18.289236,17.762744,17.256474,16.769507,16.300970,15.850038,15.415925,14.997888
30,28.991834,28.027175,27.103830,26.219731,25.372925,24.561571,23.783929,23.038356,22.323300,21.637293
40,38.544175,37.155177,35.829447,34.563640,33.354607,32.199387,31.095191,30.039394,29.029521,28.063242
50,48.072287,46.237163,44.489493,42.824462,41.237551,39.724517,38.281377,36.904387,35.590028,34.334993
60,57.581137,55.282647,53.097640,51.019669,49.042692,47.161049,45.369436,43.662878,42.036706,40.486540
70,67.073997,64.297887,61.662868,59.160710,56.783721,54.524703,52.376921,50.334068,48.390236,46.539891
80,76.553190,73.287318,70.191523,67.255667,64.470286,61.826537,59.316158,56.931422,54.665100,52.510431
90,86.020451,82.254245,78.688331,75.310546,72.109547,69.074749,66.196273,63.464893,60.871988,58.409500